Repository softeerbootcamp-2nd/android-luckycardgame, pull requests merged in 2023-07, with the labels that each got.

#4 [안승우] Feat : 프로젝트 생성
  .gitignore
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/io/softeer/luckycardgame/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/softeer/luckycardgame/MainActivity.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/io/softeer/luckycardgame/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: setup

#1 [박동현] 1주차 럭키보드게임 프로젝트 생성
  .gitignore
  .idea/.gitignore
  .idea/kotlinc.xml
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/example/luckycardgame/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/luckycardgame/MainActivity.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values-land/dimens.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values-w1240dp/dimens.xml
  app/src/main/res/values-w600dp/dimens.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/example/luckycardgame/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: setup

#3 [1일차] 안찬우 : 프로젝트 생성
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/hd/softeer/luckycardgame/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/hd/softeer/luckycardgame/MainActivity.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/hd/softeer/luckycardgame/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: setup

#10 [한병하] 프로젝트 생성
  .gitignore
  README.md
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/glacier/luckycardgamesofteer/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/glacier/luckycardgamesofteer/MainActivity.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/glacier/luckycardgamesofteer/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: setup

#7 [박세영] 럭키보드 게임 프로젝트 생성
  .gitignore
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/example/luckycardgame/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/luckycardgame/MainActivity.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/example/luckycardgame/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: setup

#9 [강현성] 럭키보드 게임 프로젝트 생성
  .gitignore
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/example/luckycardgame/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/luckycardgame/MainActivity.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/example/luckycardgame/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: setup

#11 [조예현] 프로젝트 생성
  .gitignore
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/example/luckycardgame/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/luckycardgame/MainActivity.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/example/luckycardgame/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: setup

#13 [박세영] 럭키카드 게임 보드 구성
  app/src/main/res/drawable/bottom_linear_round.xml
  app/src/main/res/drawable/item_linear_round.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
Labels: step1-1

#6 [안승우] Feat : 게임 보드 만들기
  README.md
  app/src/main/res/drawable/cl_card_dark_gray.xml
  app/src/main/res/drawable/cl_card_gray.xml
  app/src/main/res/drawable/cl_card_yellow.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/themes.xml
Labels: step1-1

#18 [박동현] 게임보드 Layout 구현
  README.md
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/bg_gray_light_rounded.xml
  app/src/main/res/drawable/bg_gray_rounded.xml
  app/src/main/res/drawable/bg_yellow_rounded.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: step1-1

#17 [안찬우] : 1일차 main card board 화면 구성.
  README.md
  app/.gitignore
  app/build.gradle
  app/src/main/java/hd/softeer/luckycardgame/MainActivity.kt
  app/src/main/res/drawable/bottom_card_section_background.xml
  app/src/main/res/drawable/card_section_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
Labels: step1-1

#15 [조예현] 기능 1 ) 게임보드 만들기
  README.md
  app/src/main/res/layout/activity_main.xml
Labels: step1-1

#22 [안승우] Feat: 럭키카드 클래스 구현하기
  README.md
  app/src/main/java/io/softeer/luckycardgame/MainActivity.kt
  app/src/main/java/io/softeer/luckycardgame/adapter/RecyclerItemDecoration.kt
  app/src/main/java/io/softeer/luckycardgame/card/Card.kt
  app/src/main/java/io/softeer/luckycardgame/card/CardType.kt
  app/src/main/java/io/softeer/luckycardgame/util/ViewUtil.kt
  app/src/main/res/drawable/tv_board_dark_gray.xml
  app/src/main/res/drawable/tv_board_gray.xml
Labels: step1-2

#23 [박동현] 럭키카드 클래스 구현
  README.md
  app/src/main/java/com/example/luckycardgame/MainActivity.kt
  app/src/main/java/com/example/luckycardgame/data/AnimalType.kt
  app/src/main/java/com/example/luckycardgame/data/Card.kt
Labels: step1-2

#41 [강현성] 게임보드 만들기
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: step1-1

#25 [한병하] 럭키카드 클래스 구현하기
  app/src/main/java/com/glacier/luckycardgamesofteer/AnimalInfo.kt
  app/src/main/java/com/glacier/luckycardgamesofteer/Card.kt
  app/src/main/java/com/glacier/luckycardgamesofteer/MainActivity.kt
Labels: step1-2

#28 [박세영] 카드 클래스 구현
  .idea/.gitignore
  .idea/gradle.xml
  README.md
  app/build.gradle
  app/src/main/java/com/example/luckycardgame/MainActivity.kt
  app/src/main/java/com/example/luckycardgame/model/Card.kt
  app/src/main/java/com/example/luckycardgame/model/CardType.kt
  app/src/main/java/com/example/luckycardgame/repository/CardRepository.kt
  app/src/main/java/com/example/luckycardgame/repository/CardRepositoryImpl.kt
  app/src/main/java/com/example/luckycardgame/service/CardService.kt
  app/src/main/java/com/example/luckycardgame/service/CardServiceImpl.kt
  app/src/test/java/com/example/luckycardgame/ExampleUnitTest.kt
Labels: step1-2

#30 [안찬우] : 카드 클래스 구현
  app/src/main/java/hd/softeer/luckycardgame/MainActivity.kt
  app/src/main/java/hd/softeer/luckycardgame/model/Animal.kt
  app/src/main/java/hd/softeer/luckycardgame/model/Card.kt
  app/src/main/java/hd/softeer/luckycardgame/model/CardNumber.kt
Labels: step1-2

#32 [조예현] 기능 2) 럭키 카드 클래스
  README.md
  app/src/main/java/com/example/luckycardgame/Card.kt
  app/src/main/java/com/example/luckycardgame/LuckyCard.kt
  app/src/main/java/com/example/luckycardgame/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: step1-2

#34 [한병하] 카드 나눠주기
  README.md
  app/build.gradle
  app/src/main/java/com/glacier/luckycardgamesofteer/MainActivity.kt
  app/src/main/java/com/glacier/luckycardgamesofteer/OverlapDecoration.kt
  app/src/main/java/com/glacier/luckycardgamesofteer/adapter/CardAdapter.kt
  app/src/main/java/com/glacier/luckycardgamesofteer/model/Animal.kt
  app/src/main/java/com/glacier/luckycardgamesofteer/model/Card.kt
  app/src/main/java/com/glacier/luckycardgamesofteer/model/Participant.kt
  app/src/main/res/drawable/baseline_check_24.xml
  app/src/main/res/drawable/bg_outlined.xml
  app/src/main/res/drawable/bg_radius_outlined.xml
  app/src/main/res/drawable/img_backcard.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_card.xml
  app/src/main/res/values/themes.xml
Labels: step1-3

#44 [박동현] 카드 나눠주기 구현
  README.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/luckycardgame/LuckyCardGameApplication.kt
  app/src/main/java/com/example/luckycardgame/MainActivity.kt
  app/src/main/java/com/example/luckycardgame/data/model/AnimalType.kt
  app/src/main/java/com/example/luckycardgame/data/model/Card.kt
  app/src/main/java/com/example/luckycardgame/data/model/LuckyGame.kt
  app/src/main/java/com/example/luckycardgame/data/model/User.kt
  app/src/main/java/com/example/luckycardgame/data/repo/CardRepository.kt
  app/src/main/java/com/example/luckycardgame/di/LuckyGameModule.kt
  app/src/main/java/com/example/luckycardgame/presentation/MainActivity.kt
  app/src/main/java/com/example/luckycardgame/presentation/MainActivityBindingAdapter.kt
  app/src/main/java/com/example/luckycardgame/presentation/MainActivityViewModel.kt
  app/src/main/java/com/example/luckycardgame/presentation/MyCardAdapter.kt
  app/src/main/java/com/example/luckycardgame/util/TextExtractor.kt
  app/src/main/res/drawable/bg_white_rounded_border.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/img_back.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_card.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: step1-3

#49 [안승우] Feat : 카드 나눠주기
  README.md
  app/build.gradle
  app/src/main/java/io/softeer/luckycardgame/MainActivity.kt
  app/src/main/java/io/softeer/luckycardgame/adapter/CardAdapter.kt
  app/src/main/java/io/softeer/luckycardgame/card/Card.kt
  app/src/main/java/io/softeer/luckycardgame/player/Player.kt
  app/src/main/java/io/softeer/luckycardgame/util/ViewUtil.kt
  app/src/main/res/color/segment_button_color.xml
  app/src/main/res/drawable/card_back.png
  app/src/main/res/drawable/cl_card.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/holder_card.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: step1-3

#45 [박동현] 게임로직 구현 및 테스트 케이스 작성
  README.md
  app/src/main/java/com/example/luckycardgame/data/model/LuckyGame.kt
  app/src/main/java/com/example/luckycardgame/data/model/User.kt
  app/src/test/java/com/example/luckycardgame/model/LuckyGameTest.kt
Labels: step1-4

#46 [조예현] 카드 나눠주기 구현
  README.md
  app/build.gradle
  app/src/main/java/com/example/luckycardgame/CardListAdapter.kt
  app/src/main/java/com/example/luckycardgame/LuckyCard.kt
  app/src/main/java/com/example/luckycardgame/MainActivity.kt
  app/src/main/java/com/example/luckycardgame/MarginSetBottomDecoration.kt
  app/src/main/java/com/example/luckycardgame/MarginSetDecoration.kt
  app/src/main/java/com/example/luckycardgame/Participant.kt
  app/src/main/res/drawable/backside.png
  app/src/main/res/drawable/card_view.xml
  app/src/main/res/drawable/checkicon.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/card_item.xml
Labels: step1-3

#47 [한병하] 게임로직 구현하기
  README.md
  app/build.gradle
  app/src/main/java/com/glacier/luckycardgamesofteer/AnimalInfo.kt
  app/src/main/java/com/glacier/luckycardgamesofteer/LuckyGame.kt
  app/src/main/java/com/glacier/luckycardgamesofteer/MainActivity.kt
  app/src/main/java/com/glacier/luckycardgamesofteer/model/Participant.kt
  app/src/main/res/layout/item_card_back.xml
  app/src/test/java/com/glacier/luckycardgamesofteer/ExampleUnitTest.kt
  app/src/test/java/com/glacier/luckycardgamesofteer/LuckyGameTest.kt
Labels: step1-4

#43 [강현성] 카드 나눠주기
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/luckycardgame/MainActivity.kt
  app/src/main/java/com/example/luckycardgame/adapter/CardAdapter.kt
  app/src/main/java/com/example/luckycardgame/model/Card.kt
  app/src/main/java/com/example/luckycardgame/model/CardType.kt
  app/src/main/java/com/example/luckycardgame/model/Participant.kt
  app/src/main/java/com/example/luckycardgame/model/Table.kt
  app/src/main/java/com/example/luckycardgame/viewmodel/LuckyBoardGameViewModel.kt
  app/src/main/res/drawable/baseline_check.xml
  app/src/main/res/drawable/card_background.png
  app/src/main/res/drawable/card_background_xml.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/adapter_card_item.xml
  app/src/main/res/layout/adapter_table_card_item.xml
  app/src/main/res/values/strings.xml
Labels: step1-3

#51 [박세영] 게임 로직 구현
  .idea/gradle.xml
  README.md
  app/build.gradle
  app/src/main/java/com/example/luckycardgame/MainActivity.kt
  app/src/main/java/com/example/luckycardgame/adapter/CardAdapter.kt
  app/src/main/java/com/example/luckycardgame/model/LuckyGame.kt
  app/src/main/java/com/example/luckycardgame/model/Participant.kt
  app/src/main/java/com/example/luckycardgame/repository/CardRepository.kt
  app/src/main/java/com/example/luckycardgame/repository/CardRepositoryImpl.kt
  app/src/main/java/com/example/luckycardgame/service/CardService.kt
  app/src/main/java/com/example/luckycardgame/service/CardServiceImpl.kt
  app/src/test/java/com/example/luckycardgame/ExampleUnitTest.kt
  app/src/test/java/com/example/luckycardgame/LuckyGameTest.kt
Labels: step1-4

#50 [강현성] 게임로직 구현하기
  app/build.gradle
  app/src/main/java/com/example/luckycardgame/MainActivity.kt
  app/src/main/java/com/example/luckycardgame/model/Participant.kt
  app/src/main/java/com/example/luckycardgame/model/Table.kt
  app/src/main/java/com/example/luckycardgame/viewmodel/LuckyBoardGameViewModel.kt
  app/src/test/java/com/example/luckycardgame/LuckyBoardGameViewModelTest.kt
Labels: step1-4

#57 [박동현] 게임규칙 추가하기 - 카드 뒤집기 구현
  README.md
  app/src/main/java/com/example/luckycardgame/data/model/Card.kt
  app/src/main/java/com/example/luckycardgame/data/model/LuckyGame.kt
  app/src/main/java/com/example/luckycardgame/presentation/MainActivityBindingAdapter.kt
  app/src/main/java/com/example/luckycardgame/presentation/MainActivityViewModel.kt
  app/src/main/java/com/example/luckycardgame/presentation/MyCardAdapter.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_card.xml
Labels: step1-5

#59 [조예현] 게임 로직 구현하기
  README.md
  app/src/main/java/com/example/luckycardgame/CardListAdapter.kt
  app/src/main/java/com/example/luckycardgame/LuckyCard.kt
  app/src/main/java/com/example/luckycardgame/LuckyGame.kt
  app/src/main/java/com/example/luckycardgame/MainActivity.kt
  app/src/main/java/com/example/luckycardgame/Participant.kt
  app/src/test/java/com/example/luckycardgame/LuckyCardTest.kt
Labels: step1-4

#60 [한병하] 게임규칙 추가하기
  README.md
  app/src/main/java/com/glacier/luckycardgamesofteer/LuckyGame.kt
  app/src/main/java/com/glacier/luckycardgamesofteer/MainActivity.kt
  app/src/main/java/com/glacier/luckycardgamesofteer/adapter/CardAdapter.kt
  app/src/main/java/com/glacier/luckycardgamesofteer/listener/OnCardFilpedListener.kt
  app/src/main/java/com/glacier/luckycardgamesofteer/model/Card.kt
  app/src/main/java/com/glacier/luckycardgamesofteer/model/Participant.kt
  app/src/main/res/layout/item_card.xml
  app/src/test/java/com/glacier/luckycardgamesofteer/LuckyGameTest.kt
Labels: step1-5

#61 [박동현] 게임규칙 추가하기 - 종료 조건 판단
  README.md
  app/src/main/java/com/example/luckycardgame/data/model/Card.kt
  app/src/main/java/com/example/luckycardgame/data/model/LuckyGame.kt
  app/src/main/java/com/example/luckycardgame/presentation/MainActivity.kt
  app/src/main/java/com/example/luckycardgame/presentation/MainActivityBindingAdapter.kt
  app/src/main/java/com/example/luckycardgame/presentation/MainActivityViewModel.kt
  app/src/main/java/com/example/luckycardgame/presentation/MyCardAdapter.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_card.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/example/luckycardgame/model/LuckyGameTest.kt
Labels: step1-5

#64 [조예현] 게임 규칙 추가하기
  README.md
  app/src/main/java/com/example/luckycardgame/Card.kt
  app/src/main/java/com/example/luckycardgame/CardListAdapter.kt
  app/src/main/java/com/example/luckycardgame/LuckyGame.kt
  app/src/main/java/com/example/luckycardgame/MainActivity.kt
  app/src/test/java/com/example/luckycardgame/LuckyCardTest.kt
Labels: step1-5

#67 [박세영] 게임 규칙 추가하기
  app/src/main/java/com/example/luckycardgame/MainActivity.kt
  app/src/main/java/com/example/luckycardgame/adapter/CardAdapter.kt
  app/src/main/java/com/example/luckycardgame/adapter/ItemOffsetDecoration.kt
  app/src/main/java/com/example/luckycardgame/interface/OnCardClickListener.kt
  app/src/main/java/com/example/luckycardgame/model/LuckyGame.kt
  app/src/main/java/com/example/luckycardgame/model/Participant.kt
  app/src/main/java/com/example/luckycardgame/repository/GameRepository.kt
  app/src/main/java/com/example/luckycardgame/repository/GameRepositoryImpl.kt
  app/src/main/java/com/example/luckycardgame/service/CardServiceImpl.kt
  app/src/main/java/com/example/luckycardgame/service/GameService.kt
  app/src/main/java/com/example/luckycardgame/service/GameServiceImpl.kt
  app/src/main/res/drawable/item_linear_round_turn.xml
  app/src/test/java/com/example/luckycardgame/ExampleUnitTest.kt
  app/src/test/java/com/example/luckycardgame/FindParticipantWithSevenTest.kt
  app/src/test/java/com/example/luckycardgame/FindParticipantsWithNoCardsTest.kt
  app/src/test/java/com/example/luckycardgame/FindSumAndSubResultSevenTest.kt
  app/src/test/java/com/example/luckycardgame/LuckyGameTest.kt
Labels: step1-5

#69 [박세영] 게임 결과 화면 만들기
  .idea/gradle.xml
  app/src/main/java/com/example/luckycardgame/MainActivity.kt
  app/src/main/java/com/example/luckycardgame/adapter/CardAdapter.kt
  app/src/main/java/com/example/luckycardgame/adapter/ItemOffsetDecoration.kt
  app/src/main/java/com/example/luckycardgame/model/Card.kt
  app/src/main/java/com/example/luckycardgame/model/LuckyGame.kt
  app/src/main/java/com/example/luckycardgame/model/Participant.kt
  app/src/main/java/com/example/luckycardgame/repository/GameRepository.kt
  app/src/main/java/com/example/luckycardgame/repository/GameRepositoryImpl.kt
  app/src/main/java/com/example/luckycardgame/service/GameServiceImpl.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/themes.xml
  app/src/test/java/com/example/luckycardgame/ExampleUnitTest.kt
  app/src/test/java/com/example/luckycardgame/FindParticipantWithSevenTest.kt
  app/src/test/java/com/example/luckycardgame/FindSumAndSubResultSevenTest.kt
  app/src/test/java/com/example/luckycardgame/LuckyGameTest.kt
Labels: step1-6
